sudo: false

env:
  matrix:
    - COMPILER=g++-4.9 COVERAGE=coverage GCOV=gcov-4.9
    - COMPILER=g++-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - g++-5
      
install:
  - if [ "coverage" = "$COVERAGE" ]; then echo Coverage on; fi

script:
  - echo stub
